### PR TITLE
.gitignore: add ".directory"

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by mkrautz** [comment]
Please add why in the commit message.

**Comment by davidebeatrici** [comment]
Done.

**Comment by mkrautz** [comment]
But people might not know what Dolphin is... :)

**Comment by mkrautz** [comment]
I'd be happy with:

> Dolphin, the KDE file manager,

**Comment by davidebeatrici** [comment]
Or they may confuse it with the Wii and Gamecube emulator...

**Comment by davidebeatrici** [comment]
Done! :)

**Review by mkrautz — APPROVED** [review]
LGTM

**Comment by mkrautz** [comment]
Just one thing: we usually don't capitalize after the colon in commit subjects, so that often looks odd to me in your commits/PRs.

**Comment by davidebeatrici** [comment]
Oh, sorry, going to change it right now.

**Comment by davidebeatrici** [comment]
Done.

**Comment by mkrautz** [comment]
LGTM. Feel free to merge.

**Pull request merged**
