### PR TITLE
Use Mumble license and update copyright years to include 2018

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by mkrautz** [comment]
Make the commit message more descriptive: Use Mumble LICENSE for MumblePAHelper.

Also, please fix the headers... All files still use 2005-2016... They should use ...-2017.

**Comment by davidebeatrici** [comment]
Updated to 2018.

**Review by mkrautz — APPROVED** [review]
I am happy with this change, but wait for hacst. He has raised concerned about using the Mumble license for other repos.

**Comment by mkrautz** [comment]
@hacst Ping.

**Comment by hacst** [comment]
Fine with me.

**Comment by mkrautz** [comment]
Actually, I'd prefer it if the commit title/message was more clear. Maybe "Use Mumble license and update copyright years to include 2018." or something?

**Comment by davidebeatrici** [comment]
Sounds good to me.

**Comment by Kissaki** [comment]
We name the authors in our license stuff.
Extending this from the authors of code in this repository to our mumble projects authors list means:

* If we wanted to chance the license in the future, or somebody else would like to (ask for other use) this suddenly became infeasible, because now it's not 3 authors, but a list of x
* When new authors commit to this repository we will have to add them to our main project/now generic authors file

_I had a third point which I forgot in the meantime… Anyway…_

It simplifies the licensing, and makes it a generic team of authors for both projects - that's fine [by me].

I noticed https://www.mumble.info/LICENSE is outdated, and I don't know how we generate the AUTHORS file and upload it to the same domain, but that may be insufficient now.
Other than that, this is fine by me.

**Pull request merged**
